### ISSUE TITLE
DraggablePanel error

### ISSUE THREAD

**Issue by achinverma** [pedrovgs/DraggablePanel#10]
Hi , i am using this lib and i have created a demo myself and when i run this demo i got the following errors in the library
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.demo/com.example.demo.MainActivity}: android.view.InflateException: Binary XML file line #17: Error inflating class com.github.pedrovgs.DraggablePanel
[10:21:35 AM] Manpreet Singh: 10-14 10:11:26.213: D/dalvikvm(8932): Late-enabling CheckJNI
10-14 10:11:26.373: D/AndroidRuntime(8932): Shutting down VM
10-14 10:11:26.373: W/dalvikvm(8932): threadid=1: thread exiting with uncaught exception (group=0x4192dba8)
10-14 10:11:26.433: E/AndroidRuntime(8932): FATAL EXCEPTION: main
10-14 10:11:26.433: E/AndroidRuntime(8932): Process: com.example.demo, PID: 8932
10-14 10:11:26.433: E/AndroidRuntime(8932): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.demo/com.example.demo.MainActivity}: android.view.InflateException: Binary XML file line #17: Error inflating class com.github.pedrovgs.DraggablePanel
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.app.ActivityThread.access$800(ActivityThread.java:135)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.os.Handler.dispatchMessage(Handler.java:102)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.os.Looper.loop(Looper.java:136)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.app.ActivityThread.main(ActivityThread.java:5001)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at java.lang.reflect.Method.invokeNative(Native Method)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at java.lang.reflect.Method.invoke(Method.java:515)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at dalvik.system.NativeStart.main(Native Method)
10-14 10:11:26.433: E/AndroidRuntime(8932): Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.github.pedrovgs.DraggablePanel
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:707)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.app.Activity.setContentView(Activity.java:1929)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at com.example.demo.MainActivity.onCreate(MainActivity.java:33)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.app.Activity.performCreate(Activity.java:5231)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
10-14 10:11:26.433: E/AndroidRuntime(8932):  ... 11 more
10-14 10:11:26.433: E/AndroidRuntime(8932): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.pedrovgs.DraggablePanel" on path: DexPathList[[zip file "/data/app/com.example.demo-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.demo-2, /vendor/lib, /system/lib]]
10-14 10:11:26.433: E/AndroidRuntime(8932):  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.view.LayoutInflater.createView(LayoutInflater.java:559)
10-14 10:11:26.433: E/AndroidRuntime(8932):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
10-14 10:11:26.433: E/AndroidRuntime(8932):  ... 21 more

**Comment by pedrovgs** [comment]
Please...upload your project to a public repository to be able to review what's going on

**Comment by pedrovgs** [comment]
Bump!
