### ISSUE TITLE
DraggableView topview and bottom view at runtime

### ISSUE THREAD

**Issue by salvadorjhai** [pedrovgs/DraggablePanel#104]
Hi! i need help on DraggableView.

How do i set topview and bottomview at runtime? (not using xml layout)

Can we have something like:
DraggableView.AddToTopView(View v)
DraggableView.AddToBottomView(View v)

Im no expert in java so anyone would like to help?

**Comment by pedrovgs** [comment]
Hi @salvadorjhai sorry for the late response. You can configure your fragments easily using the methods indicated in the project README.md

```java
private void initializeDraggablePanel() throws Resources.NotFoundException {
      draggablePanel.setFragmentManager(getSupportFragmentManager());
      draggablePanel.setTopFragment(placeFragment);
      draggablePanel.setBottomFragment(mapFragment);
      draggablePanel.initializeView();
}
```
