### ISSUE TITLE
top view resize isn't working in draggable panel

### ISSUE THREAD

**Issue by SarthakJoshi** [pedrovgs/DraggablePanel#109]
Hello, I'm trying to implement draggable panel in an activity, in which user can select a video to play from list view. Video will be initialized in maximized view. Everything is working as expected, till this part. As soon as the user minimize the top view of the panel, video player dimensions doesn't change. I've tried using top_view_resize attribute, but no effect. How can I use draggable view's top_view_resize attribute in the draggable panel?

**Comment by pedrovgs** [comment]
@SarthakJoshi review other issues open in this repository. Depending on the video view you are implementing the library is going to resize it or not. There are some Android SDK APIs which doesn't support resize. Sorry I'm closing this issue because it's duplicated.
