### ISSUE TITLE
How to change top view's fragment

### ISSUE THREAD

**Issue by ngnclht1102** [pedrovgs/DraggablePanel#13]
I have used Draggble Panel with top fragment is a Youtube Fragment.
But some time, my Youtube Player have been released.  So I need to re initialize a youtube fragment then set it to top fragment.
I recalled: mDragblePanel.setTopFragment(myNewYouTubeFragment), then  mDragblePanel.initializeView(). But my draggble panel is unable to drag!

Please consider me a solution!

**Comment by pedrovgs** [comment]
You can change the fragment associated as top fragment using Android Fragment Manager yourself. I'll try to implement this feature to replace fragments. You can send me a pull request with this feature if you want.

**Comment by ngnclht1102** [comment]
Thanks for your answer. Sorry because I coundn't online for a long time!  

My Draggble panel has 2 fragments, top view fragment is Youtube fragment, bottom view is a custom fragment which display other videos's list. Other video's list is loaded by a loader (data is from my server). 

The first time (call initializeView) , my draggble panel work okey with no problem. But other time I try to change content of bottom view, the bottom view positon is wrong. Some time, a part of the bottom view  is overlayed by topview.

But the problem is not occur when the bottom view data is static.

Please help me when you have time! 

Thanks you very much and sorry for poor english!!

**Comment by pedrovgs** [comment]
I need to take a look to your code. Can you upload your project to any public repository or give mi access to take a look and help you with your problem?

**Comment by ngnclht1102** [comment]
I have sended an email to you. My draggble panel is located on VideoPlayer.java. Thank you very much!

**Comment by pedrovgs** [comment]
@ngnclht1102 have you sent me an email?
