### ISSUE TITLE
Issue in  draggable pannel library

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [pedrovgs/DraggablePanel#14]
I implemented draggable pannel library in my project .  
My work flow is same as your demo , the only diffrence is behind youtube fragment i am displaying a list(in your demo you displayed imageview).
When i drag the vedio down following methods are not getting called as i checked by logs. Vedio is dragging down well. 
Methods are :
  draggablePanel.setDraggableListener(new DraggableListener() {
            s
            @Override
            public void onMaximized() {
                playVideo();
                System.out.println(" onMaximized");
            }

```
        @Override
        public void onMinimized() {

            System.out.println(" onMinimized");

            //Empty
        }

        @Override
        public void onClosedToLeft() {
            pauseVideo();
            System.out.println(" onClosedToLeft");
        }

        @Override
        public void onClosedToRight() {
            pauseVideo();
            System.out.println(" onClosedToRight");
        }
    });
```

Also when i click the list behind(when vedio is dragged down) , list click listener is not working and instead vedio is maximised again.

Please help me sort this issue

**Comment by megataps** [comment]
Hi Manpreetsinghsodhi

You should change order call listener in methods OnCreate like below:

  @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_youtube_sample);
        ButterKnife.inject(this);
        initializeYoutubeFragment();

```
   // Set listner for DraggablePannel befor init
   hookDraggablePanelListeners();

    initializeDraggablePanel();
}
```

Hope this help.

**Comment by pedrovgs** [comment]
We are going to close all your problems in #17
