### ISSUE TITLE
UI  issue in draggable panel

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [pedrovgs/DraggablePanel#15]
Hi i am sending you the screen shot of problem i am facing . When i click the listview which is behind youtube fragment, the youtube player maximizes(which is ok) but as you can see below  UI portion of listview is visible . That means fragment set at bottom(which is imageview in my case by using  setbottomfragment() method ) is not setting properly.

So what is the problem?
![device-2014-10-21-165141](https://cloud.githubusercontent.com/assets/9208230/4717469/4b1c6c82-5915-11e4-9374-2f3ebfc4a345.png)

**Comment by pedrovgs** [comment]
We are going to close all your problems in #17
