### ISSUE TITLE
Failed to find: com.google.android:youtube-android-player-api:1.0.0

### ISSUE THREAD

**Issue by vuhung3990** [pedrovgs/DraggablePanel#19]
how to solve that, i'm using android studio

**Comment by pedrovgs** [comment]
You need to configure your maven local repository to be able to provide that dependency. YouTube developers are not providing that dependency in Maven Central and you have to install it manually.

I've one section in this project README file talking about this. https://github.com/pedrovgs/DraggablePanel#building-the-sample-app
