### ISSUE TITLE
Dragging a VideoView does not rescale the video

### ISSUE THREAD

**Issue by npike** [pedrovgs/DraggablePanel#2]
It seems that if you use a VideoVideo as your DragView, that the video will not resize to fit the dragview during (or after the gesture).

This results in the video in the VideoView being cropped.

See video of demo app:  https://dl.dropboxusercontent.com/u/419977/draggablepanel_videoview_crop.mp4

**Comment by pedrovgs** [comment]
Hi!!

It's a known issue. When I created this repository I put a section inside the readme with some TODO. One of them is: "Create other draggable component to resize elements instead of scale the view. This new component is needed to drag and resize videos". 

I will do it if I have time or may be other developer could implement this feature and send me a pull request :)

**Comment by Pepeli** [comment]
Hi! Any news on that? I am trying to implement it unsuccessfully :(

**Comment by pedrovgs** [comment]
Right now I don't have time to implement this feature. I'm waiting for a pull request from a buddy, but I don't know when is going to be ready. Sorry

**Comment by Pepeli** [comment]
Thanks for your reply. I will let you know if I manage it.

**Comment by npike** [comment]
I have a hacked together version of DraggablePanel that basically _only_ handles having a scalable videoview:  https://github.com/npike/so_scalevideoview

I am not sure I would recommend using it for a production app, but for my use case it did the trick.

**Comment by pedrovgs** [comment]
Hi!

I've released a new version of this library with the version number 1.1. This new version contains the fix to use VideoView with DraggableView class and resize the VideoView instead of scale it.

Thanks for your feedback!

**Comment by vuhung3990** [comment]
<com.github.pedrovgs.DraggableView
    ..................
    draggable_view:top_view_resize="true"
