### ISSUE TITLE
DraggablePanel do not Maximize on single Tap

### ISSUE THREAD

**Issue by Amritpal33** [pedrovgs/DraggablePanel#24]
Hi,
   When the Draggable panel is in minimize mode, single click does not maximizes it. A little Drag is required to maximize it.

How can i enable/fix this.?

**Comment by pedrovgs** [comment]
That feature is not going to be implemented.

**Comment by vuhung3990** [comment]
```
    draggable_view.setOnTouchListener(new OnTouchListener() {

            @Override
            public boolean onTouch(View v, MotionEvent event) {
                if(draggable_view.isMinimized() && event.getAction() == MotionEvent.ACTION_UP){
                    draggable_view.maximize();
                }
                return false;
            }
        });
```

**Comment by ppamorim** [comment]
Fixed on #42

**Comment by ppamorim** [comment]
Found bug on #42, fixing...

**Comment by ppamorim** [comment]
Fixed on #42, working now!

**Comment by pedrovgs** [comment]
Hi @Amritpal33! @ppamorim is working on a PR to implement your requested feature. This PR will be merged and a new version of DraggablePanel will be released once the PR be ready!

**Comment by ppamorim** [comment]
@Amritpal33, feature implemented. That deserves a round of beer. If you aren't of legal age, otherwise the juice round... :)
