### ISSUE TITLE
how to disable drag event when landscape?

### ISSUE THREAD

**Issue by vuhung3990** [pedrovgs/DraggablePanel#29]
hi, when landscape videoview will fullscreen and i want to disable drag and restore drag event when portrait

**Comment by vuhung3990** [comment]
i solved, edit DraggableVIew.java

```
   if(context.getResources().getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT){
                            viewDragHelper.processTouchEvent(ev);
       }
```

**Comment by Taranlayal10** [comment]
@vuhung3990 I am having the same issue in landscape mode it gets shifted to portrait on touch. Can you tell me how u did this DraggableVIew.java does not seems to take processTouchEvent. If you can make it little bit clear that will be appreciated, Thanks
