### ISSUE TITLE
?

### ISSUE THREAD

**Issue by kekedaine** [pedrovgs/DraggablePanel#3]
can you create eclipse project ? i have much error with this maven project. please.
sorry, i speak E not well. Thanks

**Comment by pedrovgs** [comment]
You can build this project using maven or gradle, professional and most common build tools. I'm not going to support more build system, sorry.

**Comment by kekedaine** [comment]
i using maven but i has been error:
![loi](https://cloud.githubusercontent.com/assets/4715657/3490787/42b23bb8-057c-11e4-9069-5b5cc421bc80.jpg)

**Comment by adnan-SM** [comment]
@ kekedaine  : You should just use Android Studio and build it.
