### ISSUE TITLE
Getting error after implementing all jar

### ISSUE THREAD

**Issue by patelajay745** [pedrovgs/DraggablePanel#4]
08-05 12:16:24.701: E/AndroidRuntime(19177): FATAL EXCEPTION: main
08-05 12:16:24.701: E/AndroidRuntime(19177): java.lang.RuntimeException: Unable to create application com.github.pedrovgs.sample.DraggablePanelApplication: java.lang.IllegalStateException: Module adapter for class com.github.pedrovgs.sample.di.MainModule could not be loaded. Please ensure that code generation was run for this module.
08-05 12:16:24.701: E/AndroidRuntime(19177):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4593)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at android.app.ActivityThread.access$1400(ActivityThread.java:157)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at android.os.Handler.dispatchMessage(Handler.java:99)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at android.os.Looper.loop(Looper.java:176)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at android.app.ActivityThread.main(ActivityThread.java:5317)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at java.lang.reflect.Method.invokeNative(Native Method)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at java.lang.reflect.Method.invoke(Method.java:511)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at dalvik.system.NativeStart.main(Native Method)
08-05 12:16:24.701: E/AndroidRuntime(19177): Caused by: java.lang.IllegalStateException: Module adapter for class com.github.pedrovgs.sample.di.MainModule could not be loaded. Please ensure that code generation was run for this module.
08-05 12:16:24.701: E/AndroidRuntime(19177):    at dagger.internal.FailoverLoader$1.create(FailoverLoader.java:45)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at dagger.internal.FailoverLoader$1.create(FailoverLoader.java:40)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at dagger.internal.Memoizer.get(Memoizer.java:56)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at dagger.internal.FailoverLoader.getModuleAdapter(FailoverLoader.java:57)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at dagger.internal.Modules.loadModules(Modules.java:43)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at dagger.ObjectGraph$DaggerObjectGraph.makeGraph(ObjectGraph.java:174)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at dagger.ObjectGraph$DaggerObjectGraph.access$000(ObjectGraph.java:138)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at dagger.ObjectGraph.create(ObjectGraph.java:129)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at com.github.pedrovgs.sample.DraggablePanelApplication.onCreate(DraggablePanelApplication.java:39)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
08-05 12:16:24.701: E/AndroidRuntime(19177):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4590)
08-05 12:16:24.701: E/AndroidRuntime(19177):    ... 10 more

**Comment by pedrovgs** [comment]
What's your Gradle version? I'm using Gradle 1.11 and I don't have this problem compiling :S How do you reproduce it?

**Comment by pedrovgs** [comment]
Hello?

**Comment by patelajay745** [comment]
Hello

**Comment by pedrovgs** [comment]
@patelajay745 can you tell me how reproduce this error? I asked you about the gradle version you were using :)

**Comment by patelajay745** [comment]
i dont know about gradle...can you help me?

**Comment by pedrovgs** [comment]
What are you doing to get that error?

**Comment by patelajay745** [comment]
i m simply run project in emulator in adt.

**Comment by pedrovgs** [comment]
Build the application using Gradle. Clone this repository, follow README.md instructions to install YouTube player dependency and execute ./gradlew installDebug

**Comment by HagerMagdy** [comment]
would you please tell me how to Build the application using Gradle ?

**Comment by pedrovgs** [comment]
./gradlew build

**Comment by HagerMagdy** [comment]
steps please am stuck in this sample for a week ! this error is always facing me

**Comment by pedrovgs** [comment]
If you execute `./gradlew` build from your terminal inside the project directory you'll generate a build of the project.

If you execute `./gradlew installDebug` you will instal the sample project into the phone/emulator detected by `adb`.

**Comment by HagerMagdy** [comment]
ok Thanks alot i will try it now :) Thanksssssssssssssssssss

**Comment by HagerMagdy** [comment]
is it  a must to run it on android studio ? or may run in Eclipse

**Comment by pedrovgs** [comment]
You should not try to compile this project using eclipse because the build tool used in this project is Gradle and eclipse doesn't support it as should. 

To build this project you can import it using android studio or intelli j and press the play button or execute the command I told you in the previous comment.

**Comment by HagerMagdy** [comment]
Thanks a lot appreciated :)

**Comment by HagerMagdy** [comment]
I execute ./gradlew build from CMD as you said and create local.properties file in the project root with my sdk.dir but it can't find my sdk .
my local.prpoerties file is :
sdk.dir=D:\Work\Tools\adt-bundle-windows-x86-20140321\adt-bundle-windows-x86-20140321\sdk
any advice ??
the error is :
FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring project ':draggablepanel'.
  > SDK location not found. Define location with sdk.dir in the local.properties f
  ile or with an ANDROID_HOME environment variable.

**Comment by HagerMagdy** [comment]
And I added Android_Home enviromental vriable as well but it stil can't find my sdk

**Comment by ppamorim** [comment]
Why you need use Eclipse?

**Comment by HagerMagdy** [comment]
simply I need to use your  draggable panel for videos in myapp which is created and has many library projects in eclipse

**Comment by HagerMagdy** [comment]
believe it or not i build draggable panel in eclipse and create new project and add it as lib project it Works ! now i am going to investigate more in your sample code :)
Thanks a lot
