### ISSUE TITLE
(Improvement) Implement the overlay to bottom/top view

### ISSUE THREAD

**Issue by ppamorim** [pedrovgs/DraggablePanel#40]
Allow the user to move the bottom view over the top or vice-versa.

**Comment by pedrovgs** [comment]
I don't understand the effect :S do you have any schema or drawing to show me this?

**Comment by pedrovgs** [comment]
@ppamorim bump!

**Comment by ppamorim** [comment]
Like AndroidSlidingUpPanel:
https://github.com/umano/AndroidSlidingUpPanel

It only can be possible when the view is maximized.

**Comment by pedrovgs** [comment]
That's not in the original youtube component. I've added your feature to maximize minimize but this doesn't match with the feature look and feel. Sorry.

**Comment by ppamorim** [comment]
Well, I believe that the library name is DraggablePanel and not YoutubePanel...
We can be better than the Youtube itself.
But what's the need for it? Sometimes it's necessary to perform this resizing in some cases such as when the user will enter text in EditText without the keyboard being on top...

**Comment by dotgc** [comment]
I need to do this. I have a bottom view where user comments are shown and an EditText is provided for the viewing user to add comments. When the EditText gains focus and the keyboard is shown, I want to be able to overlay the bottom view on top of the top view. Right now, users can't even see the EditText box when the keyboard is open.
