### ISSUE TITLE
Why Sherlock instead Toolbar?

### ISSUE THREAD

**Issue by ppamorim** [pedrovgs/DraggablePanel#44]
I just see it's still use the Sherlock ActionBar in the library, it would not be interesting to implement on the sample Toolbar to keep up with new updates? as Sherlock went into space and the Compat is being depreciated?

**Comment by pedrovgs** [comment]
This project is using ActionBar Sherlock just for the sample code. That's not important. I used sherlock because this repository was published before Android 5.0. If the code of the sample project is not related with DraggablePanel usage I'm not going to change it. Sorry.

**Comment by ppamorim** [comment]
If you want, I can remake this sample with the new Material Design UI. :)

**Comment by pedrovgs** [comment]
No thanks, I think the usage of ActionBar Sherlock or the new Android-L features is just a detail, what's  important for this repository is the library.
