### ISSUE TITLE
Eeror in runing sample project after add darragable panel as lib project

### ISSUE THREAD

**Issue by HagerMagdy** [pedrovgs/DraggablePanel#51]
i am runing the code in eclipse and add all library needed but this error keep crashing my app , in Read Me itis supposed to build with gradle would you please help me how to run this app in gradle may be this is my problem :( 

java.lang.RuntimeException: Unable to create application com.github.pedrovgs.sample.DraggablePanelApplication: java.lang.IllegalStateException: Module adapter for class com.github.pedrovgs.sample.di.MainModule could not be loaded. Please ensure that code generation was run for this module.

**Comment by pedrovgs** [comment]
You have the library artifact uploaded to maven central. http://search.maven.org/#artifactdetails|com.github.pedrovgs|draggablepanel|1.7|

I'm not going to support eclipse for this project. Sorry.

**Comment by pedrovgs** [comment]
./gradlew build
