### ISSUE TITLE
Screen goes white when in minimize state?

### ISSUE THREAD

**Issue by bilalilyas90** [pedrovgs/DraggablePanel#53]
when I am in minimized state(at end of screen) screen goes white but when in maximized state and while dragging it is working fine... please help me.. screenshots are attached
http://prntscr.com/69yge2     (while dragging)
http://prntscr.com/69yfpa      (in minimized state)

**Comment by ppamorim** [comment]
@bilalilyas90 SurfaceView... bro!

**Comment by pedrovgs** [comment]
As @ppamorim says, the problem is related with the view you are using inside DraggablePanel not with this library.
