### ISSUE TITLE
DraggablePanel onclick Event for top view when view is minimized 

### ISSUE THREAD

**Issue by JoysonF** [pedrovgs/DraggablePanel#64]
I haven't been able to find a click event for top view when draggable panel view is minimized. I want to maximize the draggable view, on click of the top view (when its in minimized state). I am implementing the same feature as in Youtube.

**Comment by pedrovgs** [comment]
You have a method in `DraggablePanel` and `DraggableView` with name `setClickToMaximizeEnabled(boolean enableClickToMaximize)` which enables the effect you are looking for.

This is the `DraggableView`method implementation:

``` java

/**
   * Enable or disable click to maximize view when dragged view is minimized
   * If your content have a touch/click listener (like YoutubePlayer), you
   * need disable it to active this feature.
   *
   * @param enableClickToMaximize to enable or disable the click.
   */
  public void setClickToMaximizeEnabled(boolean enableClickToMaximize) {
    this.enableClickToMaximize = enableClickToMaximize;
  }

```

You can also enable this effect from your layout using `draggable_view:enable_click_to_maximize="false"` xml attribute:

``` xml

<com.github.pedrovgs.DraggableView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:draggable_view="http://schemas.android.com/apk/res-auto"
        android:id="@+id/draggable_view"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        draggable_view:top_view_id="@+id/iv_fan_art"
        draggable_view:bottom_view_id="@+id/lv_episodes"
        draggable_view:top_view_x_scale_factor="@dimen/x_scale_factor"
        draggable_view:top_view_y_scale_factor="@dimen/y_scale_factor"
        draggable_view:top_view_margin_right="@dimen/top_fragment_margin"
        draggable_view:top_view_margin_bottom="@dimen/top_fragment_margin"
        draggable_view:enable_click_to_maximize="true"
        android:background="@color/black">

        <!-- ....... -->

</com.github.pedrovgs.DraggableView>

```

Is this the answer to your question?

**Comment by JoysonF** [comment]
Thanks pedrovgs for your prompt reply. Using setClickToMaximizeEnabled  solved my query .However When using the attritube in layout file gave me the following error :Error:(17) No resource identifier found for attribute 'enable_click_to_maximize' in package 'com.github.pedrovgs.sample'.

**Comment by pedrovgs** [comment]
Are you using the library namespace like the sample shows? `xmlns:draggable_view="http://schemas.android.com/apk/res-auto"`

**Comment by JoysonF** [comment]
Yes pedrovgs, I am editing in the sample project you provided.

**Comment by pedrovgs** [comment]
Can you show me the diff? I'd like to know what you've modified to get that error.

**Comment by JoysonF** [comment]
Yes Sure.
<com.github.pedrovgs.DraggableView 
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:draggable_view="http://schemas.android.com/apk/res-auto"
        android:id="@+id/draggable_view"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:background="@color/black"
        draggable_view:bottom_view_id="@+id/iv_thumbnail"
        draggable_view:enable_click_to_maximize="false"
        draggable_view:top_view_height="@dimen/top_fragment_height"
        draggable_view:top_view_id="@+id/video_view"
        draggable_view:top_view_margin_bottom="@dimen/top_fragment_margin"
        draggable_view:top_view_margin_right="@dimen/top_fragment_margin"
        draggable_view:top_view_x_scale_factor="@dimen/x_scale_factor"
        draggable_view:top_view_y_scale_factor="@dimen/y_scale_factor">

**Comment by pedrovgs** [comment]
The correct attribute is:

``` xml
draggable_view:enable_click_to_maximize_view="false"
```

The README.md documentation is not following the attrs.xml file: https://github.com/pedrovgs/DraggablePanel/blob/develop/draggablepanel/res/values/attrs.xml. Sorry I'm going to update it.

**Comment by pedrovgs** [comment]
I've updated the README.md with the documentation updated. Is this the fix to your problem?

**Comment by JoysonF** [comment]
Yes. Thanks Again For the library :+1:  .

**Comment by pedrovgs** [comment]
You are welcome!
