### ISSUE TITLE
View Alpha and crop problem with YoutubePlayerAndroidApi

### ISSUE THREAD

**Issue by dzunghdo** [pedrovgs/DraggablePanel#68]
I'm using DraggablePanel and YoutubePlayerSupportFragment as TopFragment in my app as implemented in your sample. But I found 2 problems with this:
1. I recognize that when the DraggablePanel is minimized, the video is cropped. I tried fixing DEFAULT_TOP_VIEW_RESIZE in DraggableView to true, but the dragging animation is too lagged, not as smooth as before.
2. I setEnableHorizontalAlphaEffect(true) but when the YoutubePlayer is minimized, if I horizontally swipe the DraggableView, the player becomes transparent.

Do you have any solution for these ? 
Hope to be answered soon. Thank you.

**Comment by pedrovgs** [comment]
We've already talked about this in other issues, Youtube Library does not support alpha or size changes, that's not a problem of the library.
