### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by friederbluemle** [pedrovgs/DraggablePanel#7]
This one is easy:

Go to https://github.com/pedrovgs/DraggablePanel/branches and delete the **Stale branches**

Also: Since you now have a `master` and `develop` branch, you should set the **default branch** to `develop` in the project settings. Otherwise pull requests will target `master` by default.

**Comment by pedrovgs** [comment]
Done :) Thanks!!

**Comment by friederbluemle** [comment]
Thanks!
