### ISSUE TITLE
Error on screen rotation when minimized: JNI DETECTED ERROR IN APPLICATION

### ISSUE THREAD

**Issue by sierra-delta** [pedrovgs/DraggablePanel#73]
Android version 6.0 
When the player is minimized and I rotate the screen I get the following error:
JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethod called with pending exception java.lang.IllegalStateException: Unable to create layer for FrameLayout

Is anyone else exeriencing this?

11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethod called with pending exception java.lang.IllegalStateException: Unable to create layer for FrameLayout
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:323)
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at void android.os.Looper.loop() (Looper.java:135)
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:5417)
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:726)
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:616)
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410] 
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]     in call to CallObjectMethod
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]     from void android.os.MessageQueue.nativePollOnce(long, int)
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410] "main" prio=5 tid=1 Runnable
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   | group="main" sCount=0 dsCount=0 obj=0x73a282a0 self=0xb4d36a00
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   | sysTid=352 nice=0 cgrp=default sched=0/0 handle=0xb6f13b34
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   | state=R schedstat=( 2126617067 433271528 2520 ) utm=185 stm=27 core=1 HZ=100
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   | stack=0xbe641000-0xbe643000 stackSize=8MB
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   | held mutexes= "mutator lock"(shared held)
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #00 pc 00370aa9  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const_, art::ArtMethod_, void_)+160)
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #01 pc 003503b7  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+150)
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #02 pc 0025a6fd  /system/lib/libart.so (art::JavaVMExt::JniAbort(char const_, char const_)+740)
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #03 pc 0025add5  /system/lib/libart.so (art::JavaVMExt::JniAbortV(char const_, char const_, std::__va_list)+64)
11-06 16:41:31.301 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #04 pc 000fd1d1  /system/lib/libart.so (art::ScopedCheck::AbortF(char const_, ...)+32)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #05 pc 001022e5  /system/lib/libart.so (art::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const_, art::JniValueType_) (.constprop.95)+5072)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #06 pc 00110b73  /system/lib/libart.so (art::CheckJNI::CallMethodV(char const_, _JNIEnv_, _jobject_, _jclass_, _jmethodID_, std::__va_list, art::Primitive::Type, art::InvokeType)+534)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #07 pc 001124f1  /system/lib/libart.so (art::CheckJNI::CallObjectMethod(_JNIEnv_, _jobject_, _jmethodID_, ...)+48)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #08 pc 00002bbb  /system/lib/libnativehelper.so (jniGetReferent+94)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #09 pc 00076157  /system/lib/libandroid_runtime.so (android::NativeDisplayEventReceiver::dispatchVsync(long long, int, unsigned int)+26)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #10 pc 00076379  /system/lib/libandroid_runtime.so (android::NativeDisplayEventReceiver::handleEvent(int, int, void_)+80)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #11 pc 00012d1b  /system/lib/libutils.so (android::Looper::pollInner(int)+530)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #12 pc 00012deb  /system/lib/libutils.so (android::Looper::pollOnce(int, int_, int_, void__)+130)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #13 pc 00081b75  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv_, _jobject*, int)+22)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   native: #14 pc 0000056d  /data/dalvik-cache/arm/system@framework@boot.oat (Java_android_os_MessageQueue_nativePollOnce__JI+96)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at android.os.MessageQueue.nativePollOnce(Native method)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at android.os.MessageQueue.next(MessageQueue.java:323)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at android.os.Looper.loop(Looper.java:135)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at android.app.ActivityThread.main(ActivityThread.java:5417)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.reflect.Method.invoke!(Native method)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-06 16:41:31.302 352-352/com.myApp A/art: art/runtime/java_vm_ext.cc:410]

**Comment by ppamorim** [comment]
Tested at a 6.0 device here. No problems. Would you inform the device that happens the problem? Hardly it`s a problem with the library, but the problem can be with the beta version of Android 6.0.

**Comment by sierra-delta** [comment]
Its a Nexus 6

**Comment by ppamorim** [comment]
It`s hard to identify the problem with this simple log. Do you have tried to use the sample app or implemented this library on your application?

**Comment by ppamorim** [comment]
This can be a problem with the beta release of the Android 6. Otherwise, try to use the sample application, if it works, wait for the stable version and test it.
This library use the most common way to perform these animations. We don't have any reason to happen this bug, we don't use any JNI code here.

**Comment by sierra-delta** [comment]
Yeah this is an issue with another lib in my app. False alarm!

**Comment by pedrovgs** [comment]
:)

**Comment by ppamorim** [comment]
@pedrovgs Where are you?

**Comment by yangxuan0261** [comment]
I have same problem, how to fix it? plz help.
