### ISSUE TITLE
How to Full screen draggable panel on screen rotation

### ISSUE THREAD

**Issue by Nguyenduylinh1402** [pedrovgs/DraggablePanel#78]
I used DraggablePanel library for my app, I used fragment view for top and bottom view so i use draggable panel. At top fragment, I have a videoview, but when i rotate to landscape mode, videoview do not full screen. First, I had changed the top height in landscape mode in (land/dimens.xml), Video was full creeen, OK, but my fragment view is destroy and Video content load again. Second I use orentation config, Video save status when rotate but not full screen.
So, How can I do this on draggable panel like draggable view do in #52 
Thanks.

**Comment by ChunJR** [comment]
Hi, i facing this issue too .. this is my fullscreen code:

@Override
    public void onConfigurationChanged(final Configuration newConfig) {
        // TODO Auto-generated method stub
        super.onConfigurationChanged(newConfig);

```
    if (getActivity().getResources().getConfiguration().orientation 
                                                == Configuration.ORIENTATION_LANDSCAPE) {

        Display display = getActivity().getWindowManager().getDefaultDisplay();

        Point size = new Point();
        display.getSize(size);

        MyActivity.draggablePanel.setTopViewHeight(size.y);
```

//          MyActivity.draggablePanel.initializeView(); // i used this and it fullscreen but i can't touch my mediaplayer control

```
        Toast.makeText(getActivity(), "landscape", Toast.LENGTH_SHORT).show();
    } else if (getActivity().getResources().getConfiguration().orientation 
                                                == Configuration.ORIENTATION_PORTRAIT) {

        Resources r = getResources();
        int px = (int) TypedValue.applyDimension(
                TypedValue.COMPLEX_UNIT_DIP, 360, r.getDisplayMetrics());

        MyActivity.draggablePanel.setTopViewHeight(px);

        Toast.makeText(getActivity(), "portraite", Toast.LENGTH_SHORT).show();
    }

}
```

**Comment by Nguyenduylinh1402** [comment]
@ChunJR 
// MyActivity.draggablePanel.initializeView(); // i used this and it fullscreen
With your code, it work with draggableView, but with draggablePannel, it not work. If you use draggablepannel, Please show me more code.

**Comment by pedrovgs** [comment]
Right now the library does not support this feature. I've already opened some issues about this one, so I'm going to close this. If you want to implement full screen support without use the library I recommend you to use a different layout in landscape mode. Cheers!

**Comment by tuncaulubilge** [comment]
Had the same problem, solved it by moving the fragment to the parent layout:

```
    @Override public void onConfigurationChanged(Configuration configuration) {
        super.onConfigurationChanged(configuration);
        if (configuration.orientation == Configuration.ORIENTATION_LANDSCAPE) {
            View playerView = playerFragment.getView();
            playerParent = (ViewGroup) findViewById(R.id.drag_view);
            playerParent.removeView(playerView);
            draggablePanel.addView(playerView, playerView.getLayoutParams());
        } else if (configuration.orientation == Configuration.ORIENTATION_PORTRAIT) {
            View playerView = playerFragment.getView();
            draggablePanel.removeView(playerView);
            playerParent = (ViewGroup) findViewById(R.id.drag_view);
            playerParent.addView(playerView, playerView.getLayoutParams());
        }

        playerFragment.onOrientationChanged(configuration.orientation);
    }
```

**Comment by usmanrana07** [comment]
@tuncaulubilge your solution works.
