### ISSUE TITLE
From the minimized DraggablePanel, tryCaptureView returns false

### ISSUE THREAD

**Issue by bigstark** [pedrovgs/DraggablePanel#8]
From the minimized DraggablePanel, tryCaptureView in DraggableViewCallback returns false

I changed support.v4.app.Fragment to app.Fragment and support.v4.app.FragmentManager to app.FragmentManager.

When I don't use DraggableView with Fragment, it works very well

But I use DraggableView with Fragment or DraggablePanel, it returns false.

Please let me know how to solve this problem

**Comment by pedrovgs** [comment]
I don't understand your problem. Do you have any screenshot or any project uploaded to a public repository to see what's going on?

**Comment by pedrovgs** [comment]
Bump!
