### ISSUE TITLE
How to change the top view height in DraggablePanel

### ISSUE THREAD

**Issue by ChunJR** [pedrovgs/DraggablePanel#80]
Hello, like a status, is there a way to change the top view height when using DraggablePanel correctly?
i have try DraggablePanel.setTopViewHeight(anotherdimen); but it not working..
Thanks !!

**Comment by Nguyenduylinh1402** [comment]
@ChunJR 
Which exactly case you want to change top height ?
If you want change when rotate screen in landscape mode, you just create landscape file dimens.xml but it will destroy your topview and recreate it(You have to disable orientation config).

**Comment by pedrovgs** [comment]
This issue is related to the #78 so I'm going to close it, sorry.
