### ISSUE TITLE
Draggable Panel do not close when combine with viewpager

### ISSUE THREAD

**Issue by DanhDueExOICTIF** [pedrovgs/DraggablePanel#82]
I using Draggable Panel combine with view pager, then draggable swipe to left/right to close it is not working. Please tell me how to fix it?

**Comment by pedrovgs** [comment]
I'm so sorry @DanhDueExOICTIF but with the current implementation this feature is not supported :( We have to rewrite part of the core library to support this feature you need right now.

**Comment by DanhDueExOICTIF** [comment]
Ok. Thank sir!
