### ISSUE TITLE
Video flickering

### ISSUE THREAD

**Issue by smedic** [pedrovgs/DraggablePanel#87]
Hello everyone,

When video starts, there is a constant flickering no matter in which state the video window is.
I have tried a few hacks such as : http://stackoverflow.com/a/27307286/1374065 but without success.
Here (http://stackoverflow.com/questions/25322660/youtube-android-fragment-flickering) is a problem with flickering , but it lasts less than a half of a second (not my case).

Does anybody have this problem or I am the only one?

Thank you.

**Comment by Shuhrat-java** [comment]
I think it is because of you are using SurfaceView. Use TextureView instead of it. Problem should go away and never return back :).

**Comment by pedrovgs** [comment]
Yeap @Shuhrat-java is right.
