### ISSUE TITLE
Youtube video does not resize when minimized

### ISSUE THREAD

**Issue by sierra-delta** [pedrovgs/DraggablePanel#9]
The YouTube video in the YoutubeSampleActivity is not re-sized when you drag the video to the bottom of the screen, whereas the video in the VideoSampleActivity does.

If you could add this support to the YouTube videos that would be great.

**Comment by pedrovgs** [comment]
In YoutubeSampleActivity we are using Fragments and is not supported. If you use youtube player view instead of youtube fragment and DraggableView instead of DraggablePanel this library is resizing the video properly.
