### ISSUE TITLE
videos seems to stop or get cropped while minimization.

### ISSUE THREAD

**Issue by x2game625** [pedrovgs/DraggablePanel#91]
<?xml version="1.0" encoding="UTF-8"?>
<RelativeLayout 

xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

```
<com.github.pedrovgs.DraggableView
    xmlns:draggable_view="http://schemas.android.com/apk/res-auto"
    android:id="@+id/draggable_panel"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    draggable_view:top_view_id="@+id/youtube_fragment"
    draggable_view:bottom_view_id="@+id/list_view_expandable"
    draggable_view:top_view_x_scale_factor="@dimen/x_scale_factor"
    draggable_view:top_view_y_scale_factor="@dimen/y_scale_factor"
    draggable_view:top_view_height="@dimen/top_fragment_height"
    draggable_view:top_view_margin_right="@dimen/top_fragment_margin"
    draggable_view:top_view_margin_bottom="@dimen/top_fragment_margin"
    draggable_view:enable_minimized_horizontal_alpha_effect="false"
    draggable_view:enable_click_to_maximize_view="true"
    draggable_view:top_view_resize="true" >

    <com.example.test_view4.AnimatedExpandableListView
        android:id="@+id/list_view_expandable"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:divider="#ff0000"
        android:dividerHeight="1dp"
        android:layout_below="@+id/youtube_fragment"/>
    <FrameLayout
        android:id="@+id/youtube_fragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

</com.github.pedrovgs.DraggableView>
```

</RelativeLayout>

I love your work. I was working on a similar project when I came across your DraggablePanel at Github. I tried working with it. And now I’m stuck if it’s ok for you can you see what the problem might be for me?

I was working on your YoutubeSample but I’m having trouble when minimizing. It seem to stop the video or crops out the view.

I tried switching the true, false on the top_view_resize and fixed the ScaleTransformer, ResizeTransfomer several time but failed.

Also I tried the answer from #38  but still can’t get the video to not-stop.

So I was wondering if there was a way I can get the video to run and not be cropped while minimization.

From a Guy desperate in Korea. Thank you in advance.

**Comment by pedrovgs** [comment]
As pointed at #38 the bug is not related to the library, the bug is related to the YouTube player library. Sorry, I'm closing this issue.
